/* Phase 11 overview: the two worlds, operating model, NP-01 … NP-12, demo accounts, device matrix §2, rules §81, backend note, Definition of Done §80, visuals */
(function () {
  var DS = JFDS, D = JFP11_DOCS, L = DS.L, t = DS.t, ic = DS.ic, esc = DS.esc, B = DS.Button;
  document.getElementById('herobtns').innerHTML = B.Primary({ label: L('Buka portal klien', 'Open the client portal'), icon: 'arrow', href: D.go('client', 'CLP-001') }) +
    B.Secondary({ label: L('Sebagai Super Admin', 'As Super Admin'), icon: 'shield', href: D.go('superadmin', 'SYS-001') }) +
    B.Ghost({ label: L('Spesifikasi layar', 'Screen specifications'), icon: 'file', href: 'screens.html' }) +
    B.Ghost({ label: L('Kasus uji', 'Test cases'), icon: 'checkc', href: 'tests.html' });
  var h = '';
  h += P3.section({ id: 'worlds', icon: 'layers', title: L('Dua dunia, satu JFRESH OS', 'Two worlds, one JFRESH OS'), desc: L('Satu pengalaman klien. Satu sistem kendali. Satu JFRESH OS yang terhubung.', 'One client experience. One system of control. One connected JFRESH OS.'),
    body: '<div class="p11-worlds">' + D.WORLDS.map(function (w) {
      return '<div class="p11-world p11-world--' + w.k.toLowerCase() + '"><div class="p11-world__h"><span class="l">' + ic(w.ic) + '</span><div><b>' + t(w.t) + '</b><small>' + t(w.s) + '</small></div></div>' +
        '<p>' + t(w.d) + '</p>' + P11.chain(w.flow) + '<p class="say">' + t(w.say) + '</p>' +
        '<div class="nps">' + w.np.map(function (k) { var n = D.NP.filter(function (x) { return x.k === k; })[0]; return '<a href="#' + n.id + '">' + esc(k) + '</a>'; }).join('') + '</div>' +
        '<p class="p11-who">' + ic('user') + t(w.k === 'A' ? L('Demo: arya.jaens, mila.jaens, putu.jaens, kadek.jaens, sari.grandvista', 'Demo: arya.jaens, mila.jaens, putu.jaens, kadek.jaens, sari.grandvista') : L('Demo: rama (Super Admin), adit (System Admin), aji (Owner)', 'Demo: rama (Super Admin), adit (System Admin), aji (Owner)')) + '</p></div>';
    }).join('') + '</div>' });
  var GATES = [
    [L('Klien A tidak pernah melihat klien B', 'Client A never sees Client B'), L('Order, invoice, POD, user, komplain dan tracking dibatasi per klien dan per property di engine. mila hanya melihat Jaens Spa Center; sari.grandvista tidak pernah melihat Jaens.', 'Orders, invoices, POD, users, complaints and tracking are scoped per client and per property in the engine. mila only sees Jaens Spa Center; sari.grandvista never sees Jaens.'), 'tests.html#clp-ISO'],
    [L('Super Admin bukan approver bisnis', 'Super Admin is not a business approver'), L('Super Admin mengelola sistem. Ia tidak bisa menyetujui pembayaran, mengubah harga atau HPP, atau menutup periode finance kecuali juga memegang role bisnis itu (§63).', 'Super Admin runs the system. It cannot approve payments, change prices or HPP, or close finance periods unless it also holds that business role (§63).'), 'tests.html#sys-s63'],
    [L('Tidak ada yang hilang diam-diam', 'Nothing disappears silently'), L('Perubahan akses dan izin butuh alasan dan tercatat before/after. Master data yang dipakai hanya dinonaktifkan. Audit, invoice, POD, jurnal tidak pernah dihapus permanen.', 'Access and permission changes need a reason and are logged before/after. Used master data is only deactivated. Audit, invoices, POD, journals are never hard-deleted.'), 'tests.html#sys-NP-10']
  ];
  h += P3.section({ id: 'gates', icon: 'shield', title: L('Tiga prinsip', 'Three principles'), desc: L('Ditegakkan di engine, bukan hanya di tampilan. Menu yang disembunyikan bukan keamanan (§47).', 'Enforced in the engine, not only in the UI. Hidden menus are not security (§47).'),
    body: '<div class="p9-gates">' + GATES.map(function (x) { return '<div><b>' + t(x[0]) + '</b><p>' + t(x[1]) + '</p><p style="margin-top:var(--jf-space-2)"><a href="' + x[2] + '">' + t(L('Lihat bukti', 'See the proof')) + ' ' + ic('arrow') + '</a></p></div>'; }).join('') + '</div>' });
  h += P3.section({ id: 'model', icon: 'route', title: L('Model operasi Fase 11', 'Phase 11 operating model'), desc: L('Klik langkah untuk membuka spesifikasi layarnya.', 'Click a step to open its screen specification.'),
    body: '<div class="p11-flows">' + D.WORLDS.map(function (w) { return '<div><b>' + t(w.k === 'A' ? L('Klien', 'Client') : L('Sistem', 'System')) + '</b>' + P11.chain(w.flow) + '</div>'; }).join('') +
      '<div><b>' + t(L('Terhubung dengan fase sebelumnya (§72)', 'Connected to earlier phases (§72)')) + '</b><ul class="p7-feel">' + [
        L('Fase 4: autentikasi, role, app shell', 'Phase 4: authentication, roles, app shell'), L('Fase 5: KPI dan keputusan', 'Phase 5: KPIs and decisions'), L('Fase 6: klien, property, kontrak', 'Phase 6: clients, properties, contracts'), L('Fase 7: tracking, ETA, chat', 'Phase 7: tracking, ETA, chat'),
        L('Fase 8: status produksi', 'Phase 8: production status'), L('Fase 9: POD dan Service Completion', 'Phase 9: POD and Service Completion'), L('Fase 10: invoice, pembayaran, finance', 'Phase 10: invoices, payments, finance')
      ].map(function (f) { return '<li>' + t(f) + '</li>'; }).join('') + '</ul></div></div>' });
  h += P3.section({ id: 'np', icon: 'layers', title: L('12 Bagian NP Fase 11', 'The 12 Phase 11 NP parts'), desc: L('NP-01 sampai NP-06 untuk klien, NP-07 sampai NP-12 untuk sistem. Klik untuk langsung ke bagiannya.', 'NP-01 to NP-06 for clients, NP-07 to NP-12 for the system. Click to jump to a part.'),
    body: '<div class="p4-np">' + D.NP.map(function (n) { return '<a href="#' + n.id + '"><span class="l">' + ic(n.ic) + '</span><small>' + n.k + ' · ' + (n.w === 'A' ? 'CLIENT' : 'SYSTEM') + '</small><b>' + t(n.t) + '</b></a>'; }).join('') + '</div>' });
  D.NP.forEach(function (n, i) {
    h += P3.section({ id: n.id, n: String(i + 1).padStart(2, '0'), title: L(n.k + ' · ' + n.t[0], n.k + ' · ' + n.t[1]), desc: n.d,
      body: '<div class="p4-two"><div style="display:grid;gap:var(--jf-space-4);min-width:0">' + P11.list(n.built) + P11.links(n.links) + '</div><div style="min-width:0">' + P11.ref(n.v) + '</div></div>' });
  });
  h += P3.section({ id: 'demo', icon: 'users', title: L('Akun demo', 'Demo accounts'), desc: L('Password semua akun: jfresh123. Peran menentukan workspace, izin menentukan aksi.', 'Every account uses jfresh123. The role sets the workspace, permissions set the actions.'),
    body: P3.table([L('Username', 'Username'), L('Peran', 'Role'), L('Yang terlihat di Fase 11', 'What Phase 11 shows')], D.DEMO.map(function (r) { return ['<code class="p3-code">' + esc(r[0]) + '</code>', r[2], r[3]]; })) });
  h += P3.section({ id: 'devices', icon: 'monitor', title: L('Matriks perangkat (§2)', 'Device matrix (§2)'), desc: L('Desktop tidak pernah dikecilkan menjadi mobile; setiap perangkat dirancang ulang.', 'Desktop is never shrunk into mobile; each device is redesigned.'),
    body: '<div class="p11-dev">' + P3.table([L('NV', 'NV'), L('Area', 'Area'), L('HP', 'Mobile'), 'iPad Pro', 'Desktop'], D.DEVICES.map(function (r) { return ['<code class="p3-code">' + r[0] + '</code>', r[1], P11.tag(r[2], L('HP', 'Mobile')), P11.tag(r[3], 'iPad Pro'), P11.tag(r[4], 'Desktop')]; })) + '</div>' });
  h += P3.section({ id: 'rules', icon: 'shield', title: L('Aturan wajib (§81)', 'Non-negotiables (§81)'), desc: L('Dari brief Fase 11.', 'From the Phase 11 brief.'), body: P3.dodont(L('Selalu', 'Always'), D.RULES, L('Jangan', 'Never'), D.DONT) });
  h += P3.section({ id: 'backend', icon: 'database', title: L('Catatan untuk tim backend', 'Note for the backend team'), desc: L('Apa yang dibuktikan prototipe ini, dan apa yang wajib diulang di server.', 'What this prototype proves, and what the server must repeat.'),
    body: '<div class="p4-note">' + ic('alert') + '<div style="display:grid;gap:var(--jf-space-2)"><p><b>' + t(L('Data Fase 11 adalah data contoh (hari demo 6 Oktober 2026).', 'Phase 11 data is sample data (demo day 6 October 2026).')) + '</b> ' + t(L('Aturan portal klien ada di assets/js/jfos-clp.js (JFCLP): cakupan klien dan property, beranda, permintaan pickup, tracking, dokumen, billing baca-saja, kasus dan user klien. Aturan sistem ada di assets/js/jfos-sys.js (JFSYS): user, role, matriks izin, review akses, master data berversi, konfigurasi, template, channel, audit gabungan, keamanan, integrasi, import/export, health, backup dan retensi. Pickup menjadi order Fase 7, invoice dibaca dari ledger Fase 10, POD dari Fase 9; tidak ada data yang disalin.', 'Client portal rules live in assets/js/jfos-clp.js (JFCLP): client and property scope, home, pickup requests, tracking, documents, read-only billing, cases and client users. System rules live in assets/js/jfos-sys.js (JFSYS): users, roles, permission matrix, access review, versioned master data, configuration, templates, channels, unified audit, security, integrations, import/export, health, backup and retention. Pickups become Phase 7 orders, invoices are read from the Phase 10 ledger, POD from Phase 9; nothing is copied.')) + '</p>' +
      '<p>' + t(L('Saat backend dibangun: otorisasi dan isolasi klien diulang di setiap API (menu tersembunyi bukan keamanan); kredensial integrasi disimpan di vault dan tidak pernah dikirim ke browser; password di-hash; audit append-only di database; email, WhatsApp, push dan integrasi bank/payment nyata; backup nyata dengan uji restore.', 'When the backend is built: authorisation and client isolation are repeated on every API (hidden menus are not security); integration credentials live in a vault and never reach the browser; passwords are hashed; the audit is append-only in the database; real email, WhatsApp, push and bank/payment integrations; real backups with restore tests.')) + '</p></div></div>' });
  h += P3.section({ id: 'dod', icon: 'checkc', title: L('Definition of Done', 'Definition of Done'), desc: L('Checklist §80: setiap butir menunjuk ke bukti (kasus uji atau layar). Butir kuning menunggu backend.', '§80 checklist: every item points to its proof (test case or screen). The amber item waits for the backend.'),
    body: '<ul class="p4-dod">' + D.DOD.map(function (d) { return '<li class="' + d[1] + '">' + ic(d[1] === 'done' ? 'checkc' : 'clock') + '<span>' + t(d[0]) + (d[1] === 'backend' ? ' <small class="hint">(' + t(L('menunggu backend', 'waits for backend')) + ')</small>' : '') + '</span><a href="' + d[2] + '" aria-label="' + esc(d[2]) + '"><span>' + t(L('Lihat', 'View')) + '</span>' + ic('arrow') + '</a></li>'; }).join('') + '</ul>' });
  h += P3.section({ id: 'visuals', icon: 'image', title: L('Visual acuan Fase 11', 'Phase 11 reference visuals'), desc: L(D.VISUALS.length + ' lembar acuan yang dikirim untuk Fase 11. Klik untuk ukuran penuh.', 'The ' + D.VISUALS.length + ' reference sheets sent for Phase 11. Click for full size.'),
    body: '<div class="p4-note" style="margin-bottom:var(--jf-space-4)">' + ic('alert') + '<p>' + t(L('Sebagian besar lembar menampilkan logo lain (wordmark "J\'FRESH Laundry & Linen Care"). Aplikasi tetap memakai logo resmi J\'Fresh (assets/brand/jfresh-logo.png); logo tidak pernah dibuat ulang.', 'Most sheets show a different logo (the "J\'FRESH Laundry & Linen Care" wordmark). The app keeps the official J\'Fresh logo (assets/brand/jfresh-logo.png); the logo is never recreated.')) + '</p></div>' +
      '<div class="p11-vis">' + D.VISUALS.map(function (v) { var f = P11.src(v); return '<figure><a href="' + f + '" target="_blank" rel="noopener"><img src="' + f + '" alt="' + esc(v.k + ' · ' + v.t[1]) + '" loading="lazy"></a><figcaption><small>' + (v.k === 'DEV' ? t(L('Pola perangkat', 'Device pattern')) : esc(v.k)) + ' · ' + (v.w === 'A' ? 'CLIENT' : 'SYSTEM') + '</small><span>' + t(v.t) + '</span>' + '</figcaption></figure>'; }).join('') + '</div>' });
  P3.mount('#page', h);
  if (location.hash) { var el = document.getElementById(location.hash.slice(1)); if (el) setTimeout(function () { el.scrollIntoView(); }, 50); }
})();
