/* Phase 6 overview: commercial lifecycle, NP-01 … NP-09, demo accounts, rules, backend note, Definition of Done, visuals */
(function () {
  var DS = JFDS, D = JFCOMM_DOCS, L = DS.L, t = DS.t, ic = DS.ic, esc = DS.esc, B = DS.Button, M = D.MODEL;
  document.getElementById('herobtns').innerHTML = B.Primary({ label: L('Buka Client 360', 'Open Client 360'), icon: 'arrow', href: D.go('owner', 'CLIENT-002/CL-07') }) +
    B.Secondary({ label: L('Spesifikasi layar', 'Screen specifications'), icon: 'file', href: 'screens.html' }) +
    B.Ghost({ label: L('Kasus uji', 'Test cases'), icon: 'checkc', href: 'tests.html' });
  function chain(list) { return '<div class="p4-flow">' + list.map(function (x, i) { var id = M.links[x]; return (i ? ic('arrow') : '') + (id ? '<a href="screens.html#' + id + '"><span>' + esc(x) + '</span></a>' : '<span>' + esc(x) + '</span>'); }).join('') + '</div>'; }
  var h = '';
  h += P3.section({ id: 'model', icon: 'route', title: L('Siklus komersial', 'Commercial lifecycle'), desc: L('Satu klien. Banyak property. Tanggung jawab, kontrak, harga dan SLA yang jelas. Riwayat komersial lengkap.', 'One client. Many properties. Clear responsibility, contract, price and SLA. Full commercial history.'),
    body: '<div style="display:grid;gap:var(--jf-space-4)"><div><b>' + t(L('Alur', 'Flow')) + '</b>' + chain(M.flow) + '</div><div><b>' + t(L('Hirarki klien (§2)', 'Client hierarchy (§2)')) + '</b>' + chain(M.tree) + '</div>' +
      '<div><b>' + t(L('Contoh: Jaens Spa Group', 'Example: Jaens Spa Group')) + '</b><ul class="p6-tree" style="margin-top:var(--jf-space-2)">' +
      [['hotel', 'Jaens Spa Group', L('Klien / grup · kontak GM untuk kontrak, harga, renewal', 'Client / group · GM contact for contract, pricing, renewal')], ['building', 'Jaens Spa Center', L('Property · PIC operasional sendiri', 'Property · own operational PIC')], ['building', 'Jaens Spa Shanti', L('Property · jadwal pickup sendiri', 'Property · own pickup schedule')], ['building', 'Jaens Spa Triloka', L('Property · layanan sendiri', 'Property · own services')], ['building', 'Jaens Spa Bisma', L('Property · SLA / tarif override opsional', 'Property · optional SLA / rate override')]]
        .map(function (r, i) { return '<li style="margin-left:' + (i ? 'var(--jf-space-5)' : '0') + '">' + ic(r[0]) + esc(r[1]) + '<small>' + t(r[2]) + '</small></li>'; }).join('') + '</ul></div></div>' });
  h += P3.section({ id: 'np', icon: 'layers', title: L('9 Bagian NP Fase 6', 'The 9 Phase 6 NP parts'), desc: L('Semua berjalan di aplikasi. Klik untuk langsung ke bagiannya.', 'All of it runs in the app. Click to jump to a part.'),
    body: '<div class="p4-np">' + D.NP.map(function (n) { return '<a href="#' + n.id + '"><span class="l">' + ic(n.ic) + '</span><small>' + n.k + ' · ' + n.v + '</small><b>' + t(n.t) + '</b></a>'; }).join('') + '</div>' });
  h += P3.section({ id: 'drill', icon: 'route', title: L('Drill-down Client Health (§66)', 'Client Health drill-down (§66)'), desc: L('Setiap health score bisa dijelaskan sampai sumbernya.', 'Every health score can be explained down to its source.'),
    body: '<div class="p4-flow">' + [L('Client Health', 'Client Health'), L('Dimensi', 'Dimension'), L('Metrik', 'Metric'), 'Property', L('Layanan', 'Service'), L('Sumber transaksi / keuangan / SLA / komplain', 'Transaction / finance / SLA / complaint source')].map(function (s, i) { return (i ? ic('arrow') : '') + '<span>' + t(s) + '</span>'; }).join('') + '</div>' });
  D.NP.forEach(function (n, i) {
    h += P3.section({ id: n.id, n: String(i + 1).padStart(2, '0'), title: L(n.k + ' · ' + n.t[0], n.k + ' · ' + n.t[1]), desc: n.d,
      body: '<div class="p4-two"><div style="display:grid;gap:var(--jf-space-4);min-width:0">' + P6.list(n.built) + P6.links(n.links) + '</div><div style="min-width:0">' + P6.ref(n.v) + '</div></div>' });
  });
  h += P3.section({ id: 'demo', icon: 'users', title: L('Akun demo', 'Demo accounts'), desc: L('Password semua akun: jfresh123. Setiap peran melihat menu Fase 6 sesuai haknya (§54).', 'Every account uses jfresh123. Each role sees the Phase 6 menus its rights allow (§54).'),
    body: P3.table([L('Username', 'Username'), L('Peran', 'Role'), L('Yang terlihat di Fase 6', 'What Phase 6 shows')], [
      ['aji', L('Owner / CEO', 'Owner / CEO'), L('Semua: Client Health, revenue, profitabilitas, risiko, growth, renewal, persetujuan, audit', 'Everything: Client Health, revenue, profitability, risk, growth, renewals, approvals, audit')],
      ['ayu', L('Sales / Account Manager', 'Sales / Account Manager'), L('Klien, property, kontak, kontrak, harga, renewal, opportunity, follow-up; mengajukan, tidak menyetujui; tanpa margin', 'Clients, properties, contacts, contracts, pricing, renewals, opportunities, follow-ups; requests, never approves; no margin')],
      ['budi', 'Finance', L('Termin, limit kredit, AR, credit note, profitabilitas, risiko keuangan', 'Terms, credit limits, AR, credit notes, profitability, financial risk')],
      ['saras', 'Supervisor', L('Property, kontak operasional, layanan, SLA clock dan alert; tanpa harga dan margin', 'Properties, operational contacts, services, SLA clock and alerts; no pricing or margin')],
      ['sari.grandvista', L('Klien · Grand Vista', 'Client · Grand Vista'), L('Hanya layanan, kontrak, SLA dan dokumen milik sendiri', 'Only own services, contract, SLA and documents')],
      ['nia.hotelabc', L('Klien · Hotel ABC', 'Client · Hotel ABC'), L('Hanya data Hotel ABC; tidak pernah melihat klien lain', 'Only Hotel ABC data; never sees another client')]
    ].map(function (r) { return ['<code class="p3-code">' + r[0] + '</code>', r[1], r[2]]; })) });
  h += P3.section({ id: 'rules', icon: 'shield', title: L('Aturan wajib (§77)', 'Non-negotiables (§77)'), desc: L('Dari brief Fase 6.', 'From the Phase 6 brief.'), body: P3.dodont(L('Selalu', 'Always'), D.RULES, L('Jangan', 'Never'), D.DONT) });
  h += P3.section({ id: 'backend', icon: 'database', title: L('Catatan untuk tim backend', 'Note for the backend team'), desc: L('Apa yang dibuktikan prototipe ini, dan apa yang wajib diulang di server.', 'What this prototype proves, and what the server must repeat.'),
    body: '<div class="p4-note">' + ic('alert') + '<div style="display:grid;gap:var(--jf-space-2)"><p><b>' + t(L('Data Fase 6 adalah data contoh.', 'Phase 6 data is sample data.')) + '</b> ' + t(L('Semua aturan kontrak, versi, harga berdasarkan tanggal, SLA clock, renewal, persetujuan, health score dan audit ada di satu modul (assets/js/jfos-comm.js) yang dipakai aplikasi dan tes. Datanya dari assets/js/jfos-comm-data.js dan disimpan di browser. AR dibaca dari ledger Fase 5, tidak disalin.', 'Every contract, version, date-based pricing, SLA clock, renewal, approval, health score and audit rule lives in one module (assets/js/jfos-comm.js) shared by the app and the tests. Data comes from assets/js/jfos-comm-data.js and is kept in the browser. AR is read from the Phase 5 ledger, never copied.')) + '</p>' +
      '<p>' + t(L('Saat backend dibangun: aturan yang sama dijalankan di server; izin, cakupan klien dan isolasi portal diperiksa ulang di setiap API; file dokumen disimpan di storage dengan versi; audit ditulis di server.', 'When the backend is built: the same rules run on the server; permissions, client scope and portal isolation are checked again on every API; document files are stored with versions; the audit is written on the server.')) + '</p></div></div>' });
  h += P3.section({ id: 'dod', icon: 'checkc', title: L('Definition of Done', 'Definition of Done'), desc: L('Checklist §76: setiap butir menunjuk ke bukti. Butir kuning menunggu backend.', '§76 checklist: every item points to its proof. The amber item waits for the backend.'),
    body: '<ul class="p4-dod">' + D.DOD.map(function (d) { return '<li class="' + d[1] + '">' + ic(d[1] === 'done' ? 'checkc' : 'clock') + '<span>' + t(d[0]) + (d[1] === 'backend' ? ' <small class="hint">(' + t(L('menunggu backend', 'waits for backend')) + ')</small>' : '') + '</span><a href="' + d[2] + '" aria-label="' + esc(d[2]) + '"><span>' + t(L('Lihat', 'View')) + '</span>' + ic('arrow') + '</a></li>'; }).join('') + '</ul>' });
  h += P3.section({ id: 'visuals', icon: 'image', title: L('Visual acuan NV-01 sampai NV-09', 'Reference visuals NV-01 to NV-09'), desc: L('Semua 9 visual dan lembar ringkasannya diterima.', 'All 9 visuals and the overview sheet received.'),
    body: '<div class="p5-vis">' + D.VISUALS.map(function (v) { return '<a class="p5-v" href="../assets/brand/phase6/' + v.f + '" target="_blank" rel="noopener"><img src="../assets/brand/phase6/' + v.f + '" alt="" loading="lazy"><b>' + (v.k === 'NV-00' ? 'NV-01–09' : v.k) + '</b><span>' + t(v.t) + '</span></a>'; }).join('') + '</div>' });
  P3.mount('#page', h);
})();
