/* Phase 4 overview: NP-01 … NP-07, demo accounts, non-negotiables, backend note, Definition of Done */
(function () {
  var DS = JFDS, D = JFACCESS_DOCS, X = JFACCESS, L = DS.L, t = DS.t, ic = DS.ic, esc = DS.esc, B = DS.Button;
  document.getElementById('herobtns').innerHTML = B.Primary({ label: L('Buka aplikasi', 'Open the app'), icon: 'arrow', href: '../app/login.html' }) +
    B.Secondary({ label: L('Spesifikasi layar', 'Screen specifications'), icon: 'file', href: 'screens.html' }) +
    B.Ghost({ label: L('Kasus uji', 'Test cases'), icon: 'checkc', href: 'tests.html' });
  var h = '';
  h += P3.section({ id: 'np', icon: 'layers', title: L('7 Bagian NP Fase 4', 'The 7 Phase 4 NP parts'), desc: L('Semua sudah berjalan di aplikasi. Klik untuk langsung ke bagiannya.', 'All of it runs in the app. Click to jump to a part.'),
    body: '<div class="p4-np">' + D.NP.map(function (n) { return '<a href="#' + n.id + '"><span class="l">' + ic(n.ic) + '</span><small>' + n.k + '</small><b>' + t(n.t) + '</b></a>'; }).join('') + '</div>' });
  h += P3.section({ id: 'flow', icon: 'route', title: L('Alur resolusi akses', 'Access resolution flow'), desc: L('Dijalankan setiap login dan setiap pemeriksaan sesi. User tidak pernah memilih peran sendiri.', 'Runs on every sign-in and every session check. Users never pick their own role.'),
    body: '<div class="p4-flow">' + [L('User', 'User'), L('Status Akun', 'Account Status'), L('Data Karyawan', 'Employee Link'), L('Peran', 'Role'), L('Plant', 'Plant'), L('Hak Akses', 'Permissions'), L('Menu', 'Navigation'), L('Halaman Awal', 'Landing')].map(function (s, i) { return (i ? ic('arrow') : '') + '<span>' + t(s) + '</span>'; }).join('') + '</div>' });
  D.NP.forEach(function (n, i) {
    h += P3.section({ id: n.id, n: '0' + (i + 1), title: L(n.k + ' · ' + n.t[0], n.k + ' · ' + n.t[1]), desc: n.d,
      body: '<div class="p4-two"><div style="display:grid;gap:var(--jf-space-4);min-width:0">' + P4.list(n.built) + P4.links(n.links) + '</div><div style="min-width:0">' + P4.ref(n.v) + '</div></div>' });
  });
  h += P3.section({ id: 'demo', icon: 'users', title: L('Akun demo', 'Demo accounts'), desc: L('Semua akun memakai password jfresh123. Data hanya disimpan di browser ini.', 'Every account uses the password jfresh123. Data is kept in this browser only.'),
    body: P3.table([L('Username', 'Username'), L('Peran / kondisi', 'Role / condition'), L('Coba', 'Try')], X.DEMO.map(function (d) { return ['<code class="p3-code">' + esc(d.u) + '</code>', d.d, '<a href="../app/login.html#/?u=' + encodeURIComponent(d.u) + '">' + t(L('Masuk', 'Sign in')) + '</a>']; })) });
  h += P3.section({ id: 'rules', icon: 'shield', title: L('Aturan wajib', 'Non-negotiables'), desc: L('Dari brief Fase 4 §79.', 'From the Phase 4 brief §79.'),
    body: P3.dodont(L('Selalu', 'Always'), [L('Peran dan hak akses ditentukan otomatis', 'Role and permissions resolved automatically'), L('Least privilege', 'Least privilege'), L('Scope data per plant / klien', 'Data scoped by plant / client'), L('Audit trail', 'Audit trail'), L('Bahasa Indonesia dulu', 'Indonesian first'), L('Design system Fase 3', 'Phase 3 design system'), L('Frontline sederhana, manajemen lengkap', 'Simple frontline, comprehensive management'), L('Riwayat user tetap tersimpan', 'User history preserved')], L('Jangan', 'Never'), D.DONT) });
  h += P3.section({ id: 'backend', icon: 'database', title: L('Catatan untuk tim backend', 'Note for the backend team'), desc: L('Apa yang dibuktikan prototipe ini, dan apa yang wajib diulang di server.', 'What this prototype proves, and what the server must repeat.'),
    body: '<div class="p4-note">' + ic('alert') + '<div style="display:grid;gap:var(--jf-space-2)"><p><b>' + t(L('Prototipe ini belum punya server.', 'This prototype has no server yet.')) + '</b> ' + t(L('Semua aturan akses berjalan di satu modul (assets/js/jfos-access.js) yang dipakai login, aplikasi dan tes. Karena berjalan di browser, siapa pun bisa mengubahnya, jadi ini bukti perilaku, bukan pengamanan.', 'Every access rule runs in one module (assets/js/jfos-access.js) shared by sign-in, the app and the tests. Because it runs in the browser anyone can change it, so it proves behaviour, not security.')) + '</p>' +
      '<p>' + t(L('Saat backend dibangun: setiap API mengulang authorize() (izin + scope plant/klien) di server, password disimpan sebagai hash, sesi memakai token server dengan masa berlaku, dan audit ditulis di server. Menu yang tersembunyi di frontend tidak pernah dianggap sebagai pengaman.', 'When the backend is built: every API repeats authorize() (permission + plant/client scope) on the server, passwords are stored as hashes, sessions use server tokens with expiry, and the audit is written on the server. A menu hidden in the frontend is never treated as protection.')) + '</p></div></div>' });
  h += P3.section({ id: 'dod', icon: 'checkc', title: L('Definition of Done', 'Definition of Done'), desc: L('Setiap butir menunjuk ke bukti. Butir kuning menunggu backend.', 'Every item points to its proof. The amber item waits for the backend.'),
    body: '<ul class="p4-dod">' + D.DOD.map(function (d) { return '<li class="' + d[1] + '">' + ic(d[1] === 'done' ? 'checkc' : 'clock') + '<span>' + t(d[0]) + (d[1] === 'backend' ? ' <small class="hint">(' + t(L('menunggu backend', 'waits for backend')) + ')</small>' : '') + '</span><a href="' + d[2] + '" aria-label="' + esc(d[2]) + '"><span>' + t(L('Lihat', 'View')) + '</span>' + ic('arrow') + '</a></li>'; }).join('') + '</ul>' });
  P3.mount('#page', h);
})();
