/* Phase 10 overview: operating model, NP-01 … NP-12, demo accounts, rules, backend note, Definition of Done, visuals */
(function () {
  var DS = JFDS, D = JFFIN_DOCS, L = DS.L, t = DS.t, ic = DS.ic, esc = DS.esc, B = DS.Button, M = D.MODEL;
  document.getElementById('herobtns').innerHTML = B.Primary({ label: L('Buka CFO Financial Health', 'Open CFO Financial Health'), icon: 'arrow', href: D.go('owner', 'CFO-001') }) +
    B.Secondary({ label: L('Sebagai finance', 'As finance'), icon: 'coins', href: D.go('finance', 'ACC-001') }) +
    B.Ghost({ label: L('Spesifikasi layar', 'Screen specifications'), icon: 'file', href: 'screens.html' }) +
    B.Ghost({ label: L('Kasus uji', 'Test cases'), icon: 'checkc', href: 'tests.html' });
  function chain(list) { return '<div class="p4-flow">' + list.map(function (x, i) { var id = M.links[x]; return (i ? ic('arrow') : '') + (id ? '<a href="screens.html#' + id + '"><span>' + esc(x) + '</span></a>' : '<span>' + esc(x) + '</span>'); }).join('') + '</div>'; }
  var h = '';
  h += P3.section({ id: 'model', icon: 'route', title: L('Model operasi Fase 10', 'Phase 10 operating model'), desc: L('Input sekali. Pakai di mana saja. Telusuri setiap angka. Jelaskan setiap keputusan.', 'Enter once. Use everywhere. Trace every number. Explain every decision.'),
    body: '<div class="p10-flows">' + M.flows.map(function (f) { return '<div><b>' + t(f.n) + '</b>' + chain(f.list) + '</div>'; }).join('') +
      '<div><b>' + t(L('Finance JFRESH harus', 'JFRESH finance must')) + '</b><ul class="p7-feel">' + M.feel.map(function (f) { return '<li>' + t(f) + '</li>'; }).join('') + '</ul></div></div>' });
  var GATES = [
    [L('Telusuri setiap angka', 'Trace every number'), L('Jurnal → invoice → Billing Ready → delivery → order → klien. Biaya → invoice supplier → PO → GRN → supplier. Tidak ada angka tanpa sumber.', 'Journal → invoice → Billing Ready → delivery → order → client. Expense → supplier invoice → PO → GRN → supplier. No figure without a source.'), D.go('finance', 'ACC-003')],
    [L('Riwayat tidak ditimpa', 'History is never overwritten'), L('HPP, harga, berat, ambang rasio dan bobot model berversi. Periode tertutup hanya berubah lewat proses terkontrol.', 'HPP, prices, weights, ratio thresholds and model weights are versioned. Closed periods change only through a controlled process.'), D.go('finance', 'HPP-004')],
    [L('Keputusan bisa dijelaskan', 'Decisions are explainable'), L('Setiap skor menunjukkan input, bobot, nilai, target, kontribusi, asumsi dan kesegaran data. Ekspansi tidak pernah dari satu metrik.', 'Every score shows inputs, weights, values, targets, contribution, assumptions and data freshness. Expansion never rests on one metric.'), D.go('owner', 'CFO-003')]
  ];
  h += P3.section({ id: 'gates', icon: 'shield', title: L('Tiga prinsip', 'Three principles'), desc: L('Ditegakkan di engine, bukan hanya di tampilan.', 'Enforced in the engine, not only in the UI.'),
    body: '<div class="p9-gates">' + GATES.map(function (x) { return '<div><b>' + t(x[0]) + '</b><p>' + t(x[1]) + '</p><p style="margin-top:var(--jf-space-2)"><a href="' + x[2] + '">' + t(L('Buka', 'Open')) + ' ' + ic('arrow') + '</a></p></div>'; }).join('') + '</div>' });
  h += P3.section({ id: 'np', icon: 'layers', title: L('12 Bagian NP Fase 10', 'The 12 Phase 10 NP parts'), desc: L('Semua berjalan di aplikasi. Klik untuk langsung ke bagiannya.', 'All of it runs in the app. Click to jump to a part.'),
    body: '<div class="p4-np">' + D.NP.map(function (n) { return '<a href="#' + n.id + '"><span class="l">' + ic(n.ic) + '</span><small>' + n.k + (n.v ? ' · ' + n.v : '') + '</small><b>' + t(n.t) + '</b></a>'; }).join('') + '</div>' });
  D.NP.forEach(function (n, i) {
    h += P3.section({ id: n.id, n: String(i + 1).padStart(2, '0'), title: L(n.k + ' · ' + n.t[0], n.k + ' · ' + n.t[1]), desc: n.d,
      body: '<div class="p4-two"><div style="display:grid;gap:var(--jf-space-4);min-width:0">' + P10.list(n.built) + P10.links(n.links) + '</div><div style="min-width:0">' + P10.ref(n.v) + '</div></div>' });
  });
  h += P3.section({ id: 'demo', icon: 'users', title: L('Akun demo', 'Demo accounts'), desc: L('Password semua akun: jfresh123. Peran menentukan workspace, izin menentukan aksi.', 'Every account uses jfresh123. The role sets the workspace, permissions set the actions.'),
    body: P3.table([L('Username', 'Username'), L('Peran', 'Role'), L('Yang terlihat di Fase 10', 'What Phase 10 shows')], [
      ['aji', L('Owner / CEO (desktop)', 'Owner / CEO (desktop)'), L('CFO Financial Health, 12 rasio, skor kesehatan, keputusan scale-up, skenario, aksi; HPP, harga, profitabilitas klien; persetujuan capex dan harga', 'CFO Financial Health, 12 ratios, health score, scale-up decisions, scenarios, actions; HPP, prices, client profitability; capex and price approval')],
      ['budi', L('Finance / CFO admin (desktop)', 'Finance / CFO admin (desktop)'), L('Akuntansi, jurnal, periode, kas & bank, billing & AR, biaya & AP, costing, budget, rekonsiliasi, monthly close, penyusutan', 'Accounting, journals, periods, cash & bank, billing & AR, expense & AP, costing, budget, reconciliation, monthly close, depreciation')],
      ['rai', L('Supply / Purchasing (iPad)', 'Supply / Purchasing (iPad)'), L('Persediaan, mutasi, opname, PR, RFQ, PO, penerimaan, supplier; tanpa data CFO', 'Inventory, movements, stock count, PR, RFQ, PO, receiving, suppliers; no CFO data')],
      ['komang', L('Asset Admin (iPad)', 'Asset Admin (iPad)'), L('Register aset, link mesin, penyusutan (baca), garansi, transfer, siklus hidup', 'Asset register, machine link, depreciation (read), warranty, transfer, lifecycle')],
      ['dewi', L('Operations Manager', 'Operations Manager'), L('HPP, konsumsi, kapasitas, persediaan, mesin, biaya operasional; persetujuan penyesuaian stok', 'HPP, consumption, capacity, inventory, machines, operating cost; stock adjustment approval')]
    ].map(function (r) { return ['<code class="p3-code">' + r[0] + '</code>', r[1], r[2]]; })) });
  h += P3.section({ id: 'rules', icon: 'shield', title: L('Aturan wajib (§101)', 'Non-negotiables (§101)'), desc: L('Dari brief Fase 10.', 'From the Phase 10 brief.'), body: P3.dodont(L('Selalu', 'Always'), D.RULES, L('Jangan', 'Never'), D.DONT) });
  h += P3.section({ id: 'backend', icon: 'database', title: L('Catatan untuk tim backend', 'Note for the backend team'), desc: L('Apa yang dibuktikan prototipe ini, dan apa yang wajib diulang di server.', 'What this prototype proves, and what the server must repeat.'),
    body: '<div class="p4-note">' + ic('alert') + '<div style="display:grid;gap:var(--jf-space-2)"><p><b>' + t(L('Data Fase 10 adalah data contoh (April–Oktober 2026), saldo dan ledger dibangun dari jurnal seimbang.', 'Phase 10 data is sample data (April–October 2026); balances and the ledger are built from balanced journals.')) + '</b> ' + t(L('Semua aturan akuntansi, kas, AR, AP, HPP, berat, harga, persediaan, purchasing, aset, budget, rekonsiliasi, close, rasio, keputusan dan skenario ada di modul engine (assets/js/jfos-fin*.js) yang dipakai aplikasi dan tes. Klien, kontrak dan rate card dibaca dari Fase 6; volume, mesin dan kapasitas dari Fase 8; Billing Ready dari Fase 9; keputusan, race dan KPI ditulis ke Fase 5. Tidak ada data yang disalin.', 'Every accounting, cash, AR, AP, HPP, weight, price, inventory, purchasing, asset, budget, reconciliation, close, ratio, decision and scenario rule lives in the engine modules (assets/js/jfos-fin*.js) shared by the app and the tests. Clients, contracts and rate cards are read from Phase 6; volume, machines and capacity from Phase 8; Billing Ready from Phase 9; decisions, races and KPIs are written to Phase 5. Nothing is copied.')) + '</p>' +
      '<p>' + t(L('Saat backend dibangun: otorisasi diulang di setiap API (tombol tersembunyi bukan keamanan); data sensitif (bank, payroll, margin, harga supplier, profitabilitas klien, rasio, keputusan investasi) dienkripsi dan dibatasi; ledger append-only dengan periode terkunci di database; bukti dan dokumen disimpan di storage; mutasi bank dan e-Faktur diintegrasikan nyata.', 'When the backend is built: authorisation is repeated on every API (hidden buttons are not security); sensitive data (bank, payroll, margin, supplier prices, client profitability, ratios, investment decisions) is encrypted and restricted; the ledger is append-only with periods locked in the database; evidence and documents go to storage; bank statements and e-Faktur are integrated for real.')) + '</p></div></div>' });
  h += P3.section({ id: 'dod', icon: 'checkc', title: L('Definition of Done', 'Definition of Done'), desc: L('Checklist §100: setiap butir menunjuk ke bukti. Butir kuning menunggu backend.', '§100 checklist: every item points to its proof. The amber item waits for the backend.'),
    body: '<ul class="p4-dod">' + D.DOD.map(function (d) { return '<li class="' + d[1] + '">' + ic(d[1] === 'done' ? 'checkc' : 'clock') + '<span>' + t(d[0]) + (d[1] === 'backend' ? ' <small class="hint">(' + t(L('menunggu backend', 'waits for backend')) + ')</small>' : '') + '</span><a href="' + d[2] + '" aria-label="' + esc(d[2]) + '"><span>' + t(L('Lihat', 'View')) + '</span>' + ic('arrow') + '</a></li>'; }).join('') + '</ul>' });
  h += P3.section({ id: 'visuals', icon: 'image', title: L('Visual acuan Fase 10', 'Phase 10 reference visuals'), desc: L('Lembar acuan NV-01 sampai NV-10 dan NV-11 sampai NV-12 yang dikirim untuk Fase 10.', 'The NV-01 to NV-10 and NV-11 to NV-12 reference sheets sent for Phase 10.'),
    body: '<div class="p10-sheets">' + ['a', 'b'].map(function (k) { var f = '../assets/brand/phase10/' + D.SHEETS[k]; return '<a class="p9-sheet" href="' + f + '" target="_blank" rel="noopener"><img src="' + f + '" alt="' + (k === 'a' ? 'NV-01 – NV-10' : 'NV-11 – NV-12') + '" loading="lazy"></a>'; }).join('') + '</div>' });
  P3.mount('#page', h);
})();
