/* Phase 8 overview: execution model, the three team workspaces, NP-01 … NP-12, demo accounts, rules, backend note, Definition of Done, visuals */
(function () {
  var DS = JFDS, D = JFPROD_DOCS, L = DS.L, t = DS.t, ic = DS.ic, esc = DS.esc, B = DS.Button, M = D.MODEL;
  document.getElementById('herobtns').innerHTML = B.Primary({ label: L('Buka Command Center', 'Open the Command Center'), icon: 'arrow', href: D.go('supervisor', 'PROD-CMD-001') }) +
    B.Secondary({ label: L('Sebagai Team 1', 'As Team 1'), icon: 'inbox', href: D.go('prod1', 'HOM-T1-001') }) +
    B.Ghost({ label: L('Spesifikasi layar', 'Screen specifications'), icon: 'file', href: 'screens.html' }) +
    B.Ghost({ label: L('Kasus uji', 'Test cases'), icon: 'checkc', href: 'tests.html' });
  function chain(list) { return '<div class="p4-flow">' + list.map(function (x, i) { var id = M.links[x]; return (i ? ic('arrow') : '') + (id ? '<a href="screens.html#' + id + '"><span>' + esc(x) + '</span></a>' : '<span>' + esc(x) + '</span>'); }).join('') + '</div>'; }
  var h = '';
  h += P3.section({ id: 'model', icon: 'route', title: L('Model eksekusi Fase 8', 'Phase 8 execution model'), desc: L('Dari cucian datang sampai siap kirim, dengan handover resmi di setiap pergantian tim.', 'From arrival to ready to deliver, with a formal handover at every team change.'),
    body: '<div style="display:grid;gap:var(--jf-space-4)"><div><b>' + t(L('Alur', 'Flow')) + '</b>' + chain(M.flow) + '</div>' +
      '<div><b>' + t(L('Produksi JFRESH harus terasa', 'JFRESH production must feel')) + '</b><ul class="p7-feel">' + M.feel.map(function (f) { return '<li>' + t(f) + '</li>'; }).join('') + '</ul></div></div>' });
  var TEAMS = [
    [L('Team 1 · Receiving & Persiapan', 'Team 1 · Receiving & Preparation'), L('Receiving, timbang, hitung, selisih, sorting, batch, kirim ke Team 2.', 'Receiving, weighing, counting, differences, sorting, batches, send to Team 2.'), D.go('prod1', 'HOM-T1-001')],
    [L('Team 2 · Washing & Drying', 'Team 2 · Washing & Drying'), L('Terima batch, MULAI CUCI, MULAI KERING, kirim ke Team 3.', 'Accept batches, MULAI CUCI, MULAI KERING, send to Team 3.'), D.go('prod2', 'HOM-T2-001')],
    [L('Team 3 · Finishing, QC & Packing', 'Team 3 · Finishing, QC & Packing'), L('Finishing, QC LULUS / ADA MASALAH, packing, label, siap kirim, serahkan ke Logistics.', 'Finishing, QC LULUS / ADA MASALAH, packing, labels, ready to deliver, hand over to Logistics.'), D.go('prod3', 'HOM-T3-001')],
    [L('Supervisor · Command Center', 'Supervisor · Command Center'), L('Live board 8 tahap, kapasitas, mesin, bottleneck, telusur batch, KPI, approval checklist.', '8-stage live board, capacity, machines, bottlenecks, batch trace, KPI, checklist approval.'), D.go('supervisor', 'PROD-CMD-001')],
    [L('Maintenance', 'Maintenance'), L('Jadwal preventive, SOP mesin, work order, downtime, riwayat.', 'Preventive schedule, machine SOPs, work orders, downtime, history.'), D.go('maint', 'MNT-001')]
  ];
  h += P3.section({ id: 'teams', icon: 'users', title: L('Satu workspace per tim (§4)', 'One workspace per team (§4)'), desc: L('Setiap iPad hanya menampilkan pekerjaan timnya sendiri.', 'Each iPad shows only its own team’s work.'),
    body: '<div class="p8-teams">' + TEAMS.map(function (x) { return '<div><b>' + t(x[0]) + '</b><p>' + t(x[1]) + '</p><p style="margin-top:var(--jf-space-2)"><a href="' + x[2] + '">' + t(L('Buka', 'Open')) + ' ' + ic('arrow') + '</a></p></div>'; }).join('') + '</div>' });
  h += P3.section({ id: 'np', icon: 'layers', title: L('12 Bagian NP Fase 8', 'The 12 Phase 8 NP parts'), desc: L('Semua berjalan di aplikasi. Klik untuk langsung ke bagiannya.', 'All of it runs in the app. Click to jump to a part.'),
    body: '<div class="p4-np">' + D.NP.map(function (n) { return '<a href="#' + n.id + '"><span class="l">' + ic(n.ic) + '</span><small>' + n.k + (n.v ? ' · ' + n.v : '') + '</small><b>' + t(n.t) + '</b></a>'; }).join('') + '</div>' });
  D.NP.forEach(function (n, i) {
    var ref = n.v ? P8.ref(n.v) : '';
    h += P3.section({ id: n.id, n: String(i + 1).padStart(2, '0'), title: L(n.k + ' · ' + n.t[0], n.k + ' · ' + n.t[1]), desc: n.d,
      body: ref ? '<div class="p4-two"><div style="display:grid;gap:var(--jf-space-4);min-width:0">' + P8.list(n.built) + P8.links(n.links) + '</div><div style="min-width:0">' + ref + '</div></div>'
        : '<div style="display:grid;gap:var(--jf-space-4);min-width:0">' + P8.list(n.built) + P8.links(n.links) + '</div>' });
  });
  h += P3.section({ id: 'demo', icon: 'users', title: L('Akun demo', 'Demo accounts'), desc: L('Password semua akun: jfresh123. Setiap peran melihat menu Fase 8 sesuai haknya (§85).', 'Every account uses jfresh123. Each role sees the Phase 8 menus its rights allow (§85).'),
    body: P3.table([L('Username', 'Username'), L('Peran', 'Role'), L('Yang terlihat di Fase 8', 'What Phase 8 shows')], [
      ['putu', L('Team 1 · Receiving & Persiapan', 'Team 1 · Receiving & Preparation'), L('Beranda Team 1, receiving, timbang, selisih, sorting, batch, handover 2, checklist', 'Team 1 home, receiving, weighing, differences, sorting, batches, handover 2, checklist')],
      ['arta', L('Team 2 · Washing & Drying', 'Team 2 · Washing & Drying'), L('Beranda Team 2, terima handover, washing, drying, handover 3, status mesin, checklist', 'Team 2 home, accept handover, washing, drying, handover 3, machine status, checklist')],
      ['luh', L('Team 3 · Finishing, QC & Packing', 'Team 3 · Finishing, QC & Packing'), L('Beranda Team 3, finishing, QC, rewash, packing, label, siap kirim, handover 4, checklist', 'Team 3 home, finishing, QC, rewash, packing, labels, ready, handover 4, checklist')],
      ['oka', L('Teknisi maintenance', 'Maintenance technician'), L('Dashboard, kalender, mesin, checklist SOP, riwayat, work order', 'Dashboard, calendar, machines, SOP checklist, history, work orders')],
      ['saras', L('Supervisor produksi', 'Production supervisor'), L('Semua di atas plus Command Center, kapasitas, KPI, master & approval checklist, verifikasi work order', 'All of the above plus Command Center, capacity, KPI, checklist master & approval, work order verification')],
      ['aji', L('Owner / CEO', 'Owner / CEO'), L('Command Center, KPI, telusur batch, status mesin, ringkasan checklist & maintenance (baca saja)', 'Command Center, KPI, batch trace, machine status, checklist & maintenance summary (read only)')],
      ['ketut', 'Driver', L('Ambil di Plant: TERIMA HANDOVER paket siap kirim, lalu alur delivery Fase 7', 'Plant Pickup: TERIMA HANDOVER of ready packages, then the Phase 7 delivery flow')]
    ].map(function (r) { return ['<code class="p3-code">' + r[0] + '</code>', r[1], r[2]]; })) });
  h += P3.section({ id: 'rules', icon: 'shield', title: L('Aturan wajib (§92)', 'Non-negotiables (§92)'), desc: L('Dari brief Fase 8.', 'From the Phase 8 brief.'), body: P3.dodont(L('Selalu', 'Always'), D.RULES, L('Jangan', 'Never'), D.DONT) });
  h += P3.section({ id: 'backend', icon: 'database', title: L('Catatan untuk tim backend', 'Note for the backend team'), desc: L('Apa yang dibuktikan prototipe ini, dan apa yang wajib diulang di server.', 'What this prototype proves, and what the server must repeat.'),
    body: '<div class="p4-note">' + ic('alert') + '<div style="display:grid;gap:var(--jf-space-2)"><p><b>' + t(L('Data Fase 8 adalah data contoh; timbangan, timer mesin dan jam disimulasikan.', 'Phase 8 data is sample data; the scale, machine timers and clock are simulated.')) + '</b> ' + t(L('Semua aturan receiving, timbang, selisih, sorting, batch, kapasitas, handover, washing, drying, finishing, QC, rewash, packing, rekonsiliasi, checklist, maintenance, work order, KPI dan audit ada di satu modul (assets/js/jfos-prod.js) yang dipakai aplikasi dan tes. Datanya dari assets/js/jfos-prod-data.js dan disimpan di browser. Manifest, order dan driver dibaca dari engine Fase 7, tidak disalin.', 'Every receiving, weighing, difference, sorting, batch, capacity, handover, washing, drying, finishing, QC, rewash, packing, reconciliation, checklist, maintenance, work order, KPI and audit rule lives in one module (assets/js/jfos-prod.js) shared by the app and the tests. Data comes from assets/js/jfos-prod-data.js and is kept in the browser. Manifests, orders and drivers are read from the Phase 7 engine, never copied.')) + '</p>' +
      '<p>' + t(L('Saat backend dibangun: berat dibaca dari timbangan digital; izin dan cakupan tim diperiksa ulang di setiap API; foto bukti disimpan di storage; status mesin dari sensor atau input operator; checklist harian dibuat terjadwal di server dari template versi yang berlaku; audit ditulis di server.', 'When the backend is built: weights are read from the digital scale; permissions and team scope are checked again on every API; photo evidence goes to storage; machine status comes from sensors or operator input; daily checklists are generated on a server schedule from the effective template version; the audit is written on the server.')) + '</p></div></div>' });
  h += P3.section({ id: 'dod', icon: 'checkc', title: L('Definition of Done', 'Definition of Done'), desc: L('Checklist §91: setiap butir menunjuk ke bukti. Butir kuning menunggu backend.', '§91 checklist: every item points to its proof. The amber item waits for the backend.'),
    body: '<ul class="p4-dod">' + D.DOD.map(function (d) { return '<li class="' + d[1] + '">' + ic(d[1] === 'done' ? 'checkc' : 'clock') + '<span>' + t(d[0]) + (d[1] === 'backend' ? ' <small class="hint">(' + t(L('menunggu backend', 'waits for backend')) + ')</small>' : '') + '</span><a href="' + d[2] + '" aria-label="' + esc(d[2]) + '"><span>' + t(L('Lihat', 'View')) + '</span>' + ic('arrow') + '</a></li>'; }).join('') + '</ul>' });
  h += P3.section({ id: 'visuals', icon: 'image', title: L('Visual acuan Fase 8', 'Phase 8 reference visuals'), desc: L('9 visual acuan yang dikirim untuk Fase 8. Inventaris dipakai sebagai acuan Fase 10; delivery lanjut di Fase 7.', 'The 9 reference visuals sent for Phase 8. Inventory is a Phase 10 reference; delivery continues in Phase 7.'),
    body: '<div class="p5-vis">' + D.VISUALS.map(function (v) { return '<a class="p5-v" href="../assets/brand/phase8/' + v.f + '" target="_blank" rel="noopener"><img src="../assets/brand/phase8/' + v.f + '" alt="" loading="lazy"><b>' + v.k + '</b><span>' + t(v.t) + '</span></a>'; }).join('') + '</div>' });
  P3.mount('#page', h);
})();
