/* Phase 12 overview: the One Data principle, four tracks, live readiness (from the engines), final flow §118, NP-01 … NP-12, demo accounts,
   device matrix §6/§113, §111 audit events, rules §117, backend note + steps to a live beta, Definition of Done, reference visual */
(function () {
  var DS = JFDS, D = JFP12_DOCS, L = DS.L, t = DS.t, ic = DS.ic, esc = DS.esc, B = DS.Button;
  document.getElementById('herobtns').innerHTML = B.Primary({ label: L('Buka Command Center', 'Open the Command Center'), icon: 'arrow', href: D.go('implead', 'BUILD-001') }) +
    B.Secondary({ label: L('Go / No-Go sebagai owner', 'Go / No-Go as the owner'), icon: 'flag', href: D.go('owner', 'LIVE-004') }) +
    B.Ghost({ label: L('Spesifikasi layar', 'Screen specifications'), icon: 'file', href: 'screens.html' }) +
    B.Ghost({ label: L('Kasus uji', 'Test cases'), icon: 'checkc', href: 'tests.html' });
  function np(k) { return D.NP.filter(function (x) { return x.k === k; })[0]; }
  var h = '';
  h += P3.section({ id: 'principle', icon: 'database', title: L('Prinsip yang dikunci di semua modul', 'The principle locked across every module'), desc: L('§1–§4 dan pernyataan akhir Fase 12. Data bisnis yang sudah ada dirujuk dan dipakai ulang, tidak pernah dibuat lagi di departemen lain.', '§1–§4 and the final Phase 12 statement. Business data that already exists is referenced and reused, never recreated in another department.'),
    body: '<div class="p12-principle"><div class="big">' + D.PRINCIPLE.map(function (x) { return '<span>' + esc(x) + '</span>'; }).join('') + '</div><ul>' + D.STATEMENT.map(function (x) { return '<li>' + ic('checkc') + '<span>' + t(x) + '</span></li>'; }).join('') + '</ul></div>' });
  var GATES = [
    [L('Satu data, tanpa input ganda', 'One data, no double entry'), L('Engine Fase 12 tidak menyimpan salinan klien, order, invoice, user, integrasi atau backup. Semua angka bisnis dibaca live dari engine pemiliknya (JFCOMM, JFLOG, JFPROD, JFDLV, JFFIN, JFACCESS, JFCLP, JFSYS). Migrasi memetakan ke id yang sudah ada.', 'The Phase 12 engines keep no copy of clients, orders, invoices, users, integrations or backups. Every business number is read live from its owner engine (JFCOMM, JFLOG, JFPROD, JFDLV, JFFIN, JFACCESS, JFCLP, JFSYS). Migration maps to existing ids.'), 'tests.html#imp-NP-02'],
    [L('Go-live adalah keputusan manusia', 'Go-live is a human decision'), L('Readiness score dan hard gate dihitung engine, tetapi GO dan START PRODUCTION hanya oleh owner, dari desktop, dan GO ditolak selama ada hard gate yang gagal. Super Admin dan System Admin tidak pernah menyetujui.', 'The engine computes the readiness score and hard gates, but GO and START PRODUCTION are the owner\'s only, from a desktop, and GO is refused while any hard gate fails. Super Admin and System Admin never approve.'), 'tests.html#go-NP-11'],
    [L('Tidak ada yang destruktif tanpa jaring pengaman', 'Nothing destructive without a safety net'), L('Reset selalu lewat dependency check, preview, snapshot dan dual approval, dieksekusi sebagai soft erase yang bisa dipulihkan. Setelah produksi, data finance historis tidak bisa dihapus permanen.', 'A reset always goes through a dependency check, preview, snapshot and dual approval, executed as a recoverable soft erase. After production starts, historical finance data cannot be permanently deleted.'), 'tests.html#go-NP-10']
  ];
  h += P3.section({ id: 'gates', icon: 'shield', title: L('Tiga prinsip', 'Three principles'), desc: L('Ditegakkan di engine, bukan hanya di tampilan.', 'Enforced in the engine, not only in the UI.'),
    body: '<div class="p9-gates">' + GATES.map(function (x) { return '<div><b>' + t(x[0]) + '</b><p>' + t(x[1]) + '</p><p style="margin-top:var(--jf-space-2)"><a href="' + x[2] + '">' + t(L('Lihat bukti', 'See the proof')) + ' ' + ic('arrow') + '</a></p></div>'; }).join('') + '</div>' });
  h += P3.section({ id: 'tracks', icon: 'layers', title: L('Empat jalur, dua belas bagian', 'Four tracks, twelve parts'), desc: L('Klik langkah untuk membuka spesifikasi layarnya, atau NP untuk langsung ke bagiannya.', 'Click a step to open its screen specification, or an NP to jump to its part.'),
    body: '<div class="p12-tracks">' + D.TRACKS.map(function (w) {
      return '<div class="p12-track p12-track--' + w.k + '"><div class="p11-world__h"><span class="l">' + ic(w.ic) + '</span><div><b>' + t(w.t) + '</b><small>' + t(w.s) + '</small></div></div>' +
        '<p>' + t(w.d) + '</p>' + P12.chain(w.flow) +
        '<div class="nps">' + w.np.map(function (k) { return '<a href="#' + np(k).id + '">' + esc(k) + '</a>'; }).join('') + '</div>' +
        '<p class="p11-who">' + ic('user') + t(L('Demo: ', 'Demo: ')) + esc(w.who) + '</p></div>';
    }).join('') + '</div>' });

  // Live readiness from the engines (as the owner, read-only).
  function readiness() {
    try {
      var G = window.JFGO, ctx = P12.ctx('aji'); if (!G || !ctx) throw new Error('engine');
      var r = G.readiness(ctx), gates = G.gates(ctx), hero = G.hero ? G.hero(ctx) : null;
      var cls = r.rec === 'GO' ? 'go' : r.rec === 'NO-GO' ? 'nogo' : 'cond';
      return '<div class="p12-ready"><div class="p12-score"><small>' + t(L('Readiness score §94', 'Readiness score §94')) + '</small><b class="big">' + esc(Math.round(r.score)) + '</b><span class="p12-rec ' + cls + '">' + t(r.recN || [r.rec, r.rec]) + '</span>' +
        (hero ? '<small>' + esc(hero.st) + ' · ' + esc(hero.version || '—') + (hero.planned ? ' · ' + t(L('rencana produksi ', 'planned production ')) + esc(hero.planned) : '') + '</small>' : '') + '</div>' +
        '<div class="p12-ready__cols"><div><h3>' + t(L('Bobot readiness', 'Readiness weights')) + '</h3><ul class="p12-dims">' + r.dims.map(function (d) {
          var v = d.v == null ? null : Math.round(d.v);
          return '<li><span>' + t(d.n) + ' <small>(' + esc(d.w) + ')</small></span><b>' + (v == null ? '—' : v + '%') + '</b><span class="bar"><i style="width:' + (v || 0) + '%"></i></span></li>';
        }).join('') + '</ul></div><div><h3>' + t(L('Hard gate §95', 'Hard gates §95')) + '</h3><ul class="p4-res">' + gates.map(function (g) {
          var v = g.ok ? '' : P12.val(g.v);
          return '<li class="' + (g.ok ? 'ok' : 'bad') + '">' + ic(g.ok ? 'checkc' : 'xc') + '<span>' + t(g.n) + (v ? '<small>' + v + '</small>' : '') + '</span></li>';
        }).join('') + '</ul></div></div></div>';
    } catch (e) {
      return '<div class="p11-nov">' + t(L('Status readiness belum bisa dimuat di halaman ini. Buka LIVE-004 di aplikasi sebagai aji.', 'The readiness status could not be loaded on this page. Open LIVE-004 in the app as aji.')) + '</div>';
    }
  }
  h += P3.section({ id: 'readiness', icon: 'gauge', title: L('Status readiness saat ini', 'Current readiness status'), desc: L('Dihitung live dari engine JFGO, JFIMP dan JFHELP di browser ini (data demo 6 Oktober 2026). Seed sengaja mulai di NO-GO: hard gate yang gagal adalah daftar pekerjaan sebelum go-live.', 'Computed live from the JFGO, JFIMP and JFHELP engines in this browser (demo data, 6 October 2026). The seed deliberately starts at NO-GO: the failing hard gates are the to-do list before go-live.'),
    body: readiness() + '<p style="margin-top:var(--jf-space-4)">' + B.Secondary({ label: L('Buka Go / No-Go sebagai aji', 'Open Go / No-Go as aji'), icon: 'arrow', href: D.go('owner', 'LIVE-004') }) + '</p>' });

  h += P3.section({ id: 'model', icon: 'route', title: L('Alur akhir Fase 12 (§118)', 'Final Phase 12 flow (§118)'), desc: L('Dari build sampai continuous improvement. Klik langkah untuk membuka spesifikasi layarnya.', 'From build to continuous improvement. Click a step to open its screen specification.'),
    body: '<div class="p12-flow">' + P12.chain(D.FLOW) + '</div>' +
      '<div style="margin-top:var(--jf-space-4)"><b style="display:block;margin-bottom:var(--jf-space-2);color:var(--jf-brand-deep)">' + t(L('Memakai ulang semua fase sebelumnya', 'Reusing every earlier phase')) + '</b><ul class="p7-feel">' + [
        L('Fase 4: autentikasi, role, app shell, Bantuan → Smart Help', 'Phase 4: authentication, roles, app shell, Help → Smart Help'), L('Fase 5: KPI untuk adopsi dan readiness', 'Phase 5: KPIs for adoption and readiness'), L('Fase 6: klien, property, kontrak, tarif (master migrasi)', 'Phase 6: clients, properties, contracts, rates (migration masters)'),
        L('Fase 7–9: order, produksi, delivery, POD (golden E2E, klasifikasi, rantai reset)', 'Phases 7–9: orders, production, delivery, POD (golden E2E, classification, reset chains)'), L('Fase 10: invoice, pembayaran, jurnal, persediaan, aset (rekonsiliasi)', 'Phase 10: invoices, payments, journals, inventory, assets (reconciliation)'),
        L('Fase 11: portal klien, user, role, integrasi, backup, audit gabungan', 'Phase 11: client portal, users, roles, integrations, backups, the unified audit')
      ].map(function (f) { return '<li>' + t(f) + '</li>'; }).join('') + '</ul></div>' });
  h += P3.section({ id: 'np', icon: 'layers', title: L('12 Bagian NP Fase 12', 'The 12 Phase 12 NP parts'), desc: L('Klik untuk langsung ke bagiannya.', 'Click to jump to a part.'),
    body: '<div class="p4-np">' + D.NP.map(function (n) { return '<a href="#' + n.id + '"><span class="l">' + ic(n.ic) + '</span><small>' + n.k + ' · ' + n.e + '</small><b>' + t(n.t) + '</b></a>'; }).join('') + '</div>' });
  D.NP.forEach(function (n, i) {
    h += P3.section({ id: n.id, n: String(i + 1).padStart(2, '0'), title: L(n.k + ' · ' + n.t[0], n.k + ' · ' + n.t[1]), desc: n.d,
      body: '<div class="p4-two"><div style="display:grid;gap:var(--jf-space-4);min-width:0">' + P12.list(n.built) + P12.links(n.links) + '</div><div style="min-width:0">' + P12.ref(n.k) + '</div></div>' });
  });
  h += P3.section({ id: 'demo', icon: 'users', title: L('Akun demo', 'Demo accounts'), desc: L('Password semua akun: jfresh123. Empat peran proyek baru (§110) ditambah owner sebagai Product Owner.', 'Every account uses jfresh123. Four new project roles (§110) plus the owner as Product Owner.'),
    body: P3.table([L('Username', 'Username'), L('Peran', 'Role'), L('Yang terlihat di Fase 12', 'What Phase 12 shows')], D.DEMO.map(function (r) { return ['<code class="p3-code">' + esc(r[0]) + '</code>', r[2], r[3]]; })) });
  h += P3.section({ id: 'devices', icon: 'monitor', title: L('Matriks perangkat (§6, §113)', 'Device matrix (§6, §113)'), desc: L('Aksi destruktif tidak pernah dioptimalkan untuk HP.', 'Destructive actions are never optimised for mobile.'),
    body: '<div class="p11-dev">' + P3.table([L('NV', 'NV'), L('Area', 'Area'), L('HP', 'Mobile'), 'iPad Pro', 'Desktop'], D.DEVICES.map(function (r) { return ['<code class="p3-code">' + r[0] + '</code>', r[1], P12.tag(r[2], L('HP', 'Mobile')), P12.tag(r[3], 'iPad Pro'), P12.tag(r[4], 'Desktop')]; })) + '</div>' });
  h += P3.section({ id: 'audit', icon: 'history', title: L('Event audit §111', 'Audit events §111'), desc: L('Kelima belas event ada di engine dan tergabung di audit trail JFSYS (modul implementation, golive, help).', 'All fifteen events exist in the engines and join the JFSYS audit trail (modules implementation, golive, help).'),
    body: '<ul class="p12-audit">' + D.AUDIT_111.map(function (a) { return '<li><code>' + esc(a[0]) + '</code><small>' + esc(a[1]) + '</small></li>'; }).join('') + '</ul>' });
  h += P3.section({ id: 'rules', icon: 'shield', title: L('Aturan wajib (§117)', 'Non-negotiables (§117)'), desc: L('Dari brief Fase 12.', 'From the Phase 12 brief.'), body: P3.dodont(L('Selalu', 'Always'), D.RULES, L('Jangan', 'Never'), D.DONT) });
  h += P3.section({ id: 'backend', icon: 'database', title: L('Catatan untuk tim backend & langkah menuju live beta', 'Note for the backend team & steps to a live beta'), desc: L('Apa yang dibuktikan prototipe ini, dan apa yang wajib dikerjakan sebelum beta testing dengan user nyata.', 'What this prototype proves, and what must be done before beta testing with real users.'),
    body: '<div class="p4-note">' + ic('alert') + '<div style="display:grid;gap:var(--jf-space-2)"><p><b>' + t(L('Data Fase 12 adalah data contoh (hari demo 6 Oktober 2026).', 'Phase 12 data is sample data (demo day 6 October 2026).')) + '</b> ' + t(L('Aturan build, One Data, QA, validasi keamanan dan keandalan ada di assets/js/jfos-imp.js (JFIMP). Migrasi, UAT, Reset Center, snapshot, cut-off, START PRODUCTION, readiness, Go/No-Go, insiden, hypercare dan improvement ada di assets/js/jfos-go.js (JFGO). Smart Help, Tanya JFRESH, PANDU SAYA, training dan Tutorial Manager ada di assets/js/jfos-help.js (JFHELP). Ketiganya membaca engine Fase 4–11 dan tidak pernah menyalin atau mengubah data bisnisnya; reset adalah soft erase yang dicatat di store JFGO.', 'Build, One Data, QA, security validation and reliability rules live in assets/js/jfos-imp.js (JFIMP). Migration, UAT, Reset Center, snapshots, cut-off, START PRODUCTION, readiness, Go/No-Go, incidents, hypercare and improvement live in assets/js/jfos-go.js (JFGO). Smart Help, Tanya JFRESH, PANDU SAYA, training and the Tutorial Manager live in assets/js/jfos-help.js (JFHELP). All three read the Phase 4–11 engines and never copy or change their business data; a reset is a soft erase recorded in the JFGO store.')) + '</p>' +
      '<p>' + t(L('Environment DEV/QA/UAT/PRODUCTION, deploy dan restore test di sini adalah model yang berjalan di browser: identifier tersamar, round trip state engine. Backend nyata harus menyediakan environment fisik terpisah, pipeline CI/CD dengan rollback, backup dan restore database nyata, otorisasi di setiap API, kredensial di vault dan integrasi email/WhatsApp nyata.', 'The DEV/QA/UAT/PRODUCTION environments, deploys and restore tests here are a model running in the browser: masked identifiers, an engine-state round trip. A real backend must provide physically separate environments, a CI/CD pipeline with rollback, real database backup and restore, authorisation on every API, credentials in a vault and real email/WhatsApp integrations.')) + '</p></div></div>' +
      '<b style="display:block;margin:var(--jf-space-4) 0 var(--jf-space-2);color:var(--jf-brand-deep)">' + t(L('Langkah menuju live beta testing', 'Steps to live beta testing')) + '</b><ol class="p12-beta">' + D.BETA.map(function (x) { return '<li>' + t(x) + '</li>'; }).join('') + '</ol>' });
  h += P3.section({ id: 'dod', icon: 'checkc', title: L('Definition of Done', 'Definition of Done'), desc: L('Diturunkan dari NP-01 sampai NP-12, §111, §116 dan §117: setiap butir menunjuk ke buktinya (kasus uji atau layar). Butir kuning menunggu backend.', 'Derived from NP-01 to NP-12, §111, §116 and §117: every item points to its proof (test case or screen). The amber item waits for the backend.'),
    body: '<ul class="p4-dod">' + D.DOD.map(function (d) { return '<li class="' + d[1] + '">' + ic(d[1] === 'done' ? 'checkc' : 'clock') + '<span>' + t(d[0]) + (d[1] === 'backend' ? ' <small class="hint">(' + t(L('menunggu backend', 'waits for backend')) + ')</small>' : '') + '</span><a href="' + d[2] + '" aria-label="' + esc(d[2]) + '"><span>' + t(L('Lihat', 'View')) + '</span>' + ic('arrow') + '</a></li>'; }).join('') + '</ul>' });
  h += P3.section({ id: 'visuals', icon: 'image', title: L('Visual acuan Fase 12', 'Phase 12 reference visual'), desc: L('Satu lembar acuan dengan dua belas panel NV-01 sampai NV-12. Klik untuk ukuran penuh.', 'One reference sheet with twelve panels NV-01 to NV-12. Click for full size.'),
    body: '<div class="p4-note" style="margin-bottom:var(--jf-space-4)">' + ic('alert') + '<p>' + t(L('Lembar ini menampilkan gambar logo "J\'Fresh Laundry" yang berbeda. Aplikasi tetap memakai logo resmi J\'Fresh (assets/brand/jfresh-logo.png); logo tidak pernah dibuat ulang.', 'This sheet shows a different "J\'Fresh Laundry" logo drawing. The app keeps the official J\'Fresh logo (assets/brand/jfresh-logo.png); the logo is never recreated.')) + '</p></div>' +
      '<div class="p11-vis p12-vis-one">' + D.VISUALS.map(function (v) { var f = P12.src(v); return '<figure><a href="' + f + '" target="_blank" rel="noopener"><img src="' + f + '" alt="' + esc(v.k + ' · ' + v.t[1]) + '" loading="lazy"></a><figcaption><small>' + esc(v.k) + '</small><span>' + t(v.t) + '</span></figcaption></figure>'; }).join('') + '</div>' });
  P3.mount('#page', h);
  if (location.hash) { var el = document.getElementById(location.hash.slice(1)); if (el) setTimeout(function () { el.scrollIntoView(); }, 50); }
})();
