/* Phase 7 overview: execution model, NP-01 … NP-10, demo accounts, rules, backend note, Definition of Done, visuals */
(function () {
  var DS = JFDS, D = JFLOG_DOCS, L = DS.L, t = DS.t, ic = DS.ic, esc = DS.esc, B = DS.Button, M = D.MODEL;
  document.getElementById('herobtns').innerHTML = B.Primary({ label: L('Buka Dispatch Board', 'Open the Dispatch Board'), icon: 'arrow', href: D.go('supervisor', 'DISPATCH-001') }) +
    B.Secondary({ label: L('Sebagai driver', 'As a driver'), icon: 'truck', href: D.go('driver', 'DRIVER-MOB-001') }) +
    B.Ghost({ label: L('Spesifikasi layar', 'Screen specifications'), icon: 'file', href: 'screens.html' }) +
    B.Ghost({ label: L('Kasus uji', 'Test cases'), icon: 'checkc', href: 'tests.html' });
  function chain(list) { return '<div class="p4-flow">' + list.map(function (x, i) { var id = M.links[x]; return (i ? ic('arrow') : '') + (id ? '<a href="screens.html#' + id + '"><span>' + esc(x) + '</span></a>' : '<span>' + esc(x) + '</span>'); }).join('') + '</div>'; }
  var h = '';
  h += P3.section({ id: 'model', icon: 'route', title: L('Model eksekusi Fase 7', 'Phase 7 execution model'), desc: L('Dari order sampai receiving, satu alur yang terhubung.', 'From order to receiving, one connected flow.'),
    body: '<div style="display:grid;gap:var(--jf-space-4)"><div><b>' + t(L('Alur', 'Flow')) + '</b>' + chain(M.flow) + '</div>' +
      '<div><b>' + t(L('Logistik JFRESH harus terasa', 'JFRESH logistics must feel')) + '</b><ul class="p7-feel">' + M.feel.map(function (f) { return '<li>' + t(f) + '</li>'; }).join('') + '</ul></div></div>' });
  h += P3.section({ id: 'np', icon: 'layers', title: L('10 Bagian NP Fase 7', 'The 10 Phase 7 NP parts'), desc: L('Semua berjalan di aplikasi. Klik untuk langsung ke bagiannya.', 'All of it runs in the app. Click to jump to a part.'),
    body: '<div class="p4-np">' + D.NP.map(function (n) { return '<a href="#' + n.id + '"><span class="l">' + ic(n.ic) + '</span><small>' + n.k + ' · ' + n.v + '</small><b>' + t(n.t) + '</b></a>'; }).join('') + '</div>' });
  h += P3.section({ id: 'privacy', icon: 'shield', title: L('Privasi lokasi (§55, §79, §80)', 'Location privacy (§55, §79, §80)'), desc: L('Lokasi adalah alat operasional, bukan pengawasan.', 'Location is an operational tool, not surveillance.'),
    body: '<div class="p4-flow">' + [L('MULAI PERJALANAN', 'MULAI PERJALANAN'), L('Lokasi dibagikan (banner)', 'Location shared (banner)'), L('Sinyal lemah → lokasi terakhir', 'Weak signal → last known'), L('Tiba di plant', 'Arrived at plant'), L('Lokasi berhenti', 'Location stops'), L('Log akses dihapus setelah 30 hari', 'Access log purged after 30 days')].map(function (s, i) { return (i ? ic('arrow') : '') + '<span>' + t(s) + '</span>'; }).join('') + '</div>' });
  D.NP.forEach(function (n, i) {
    h += P3.section({ id: n.id, n: String(i + 1).padStart(2, '0'), title: L(n.k + ' · ' + n.t[0], n.k + ' · ' + n.t[1]), desc: n.d,
      body: '<div class="p4-two"><div style="display:grid;gap:var(--jf-space-4);min-width:0">' + P7.list(n.built) + P7.links(n.links) + '</div><div style="min-width:0">' + P7.ref(n.v) + '</div></div>' });
  });
  h += P3.section({ id: 'demo', icon: 'users', title: L('Akun demo', 'Demo accounts'), desc: L('Password semua akun: jfresh123. Setiap peran melihat menu Fase 7 sesuai haknya (§82).', 'Every account uses jfresh123. Each role sees the Phase 7 menus its rights allow (§82).'),
    body: P3.table([L('Username', 'Username'), L('Peran', 'Role'), L('Yang terlihat di Fase 7', 'What Phase 7 shows')], [
      ['ketut', 'Driver', L('Hanya tugas sendiri: Hari ini, perjalanan, pickup, bukti, POD, ADA MASALAH, serahkan manifest, chat', 'Own tasks only: Today, trip, pickup, evidence, POD, ADA MASALAH, hand over manifest, chat')],
      ['saras', L('Supervisor / Dispatcher', 'Supervisor / Dispatcher'), L('Order, jadwal, dispatch, rute, driver, kendaraan, live map, masalah, timeline, KPI', 'Orders, schedules, dispatch, routes, drivers, vehicles, live map, issues, timeline, KPI')],
      ['made', L('Operator receiving plant', 'Plant receiving operator'), L('Arrival board, manifest, handover, rekonsiliasi bag, MULAI RECEIVING', 'Arrival board, manifests, handover, bag reconciliation, MULAI RECEIVING')],
      ['aji', L('Owner / CEO', 'Owner / CEO'), L('Ringkasan, KPI, masalah; live map hanya dengan alasan yang dicatat', 'Summary, KPI, issues; live map only with a logged reason')],
      ['sari.grandvista', L('Klien · Grand Vista', 'Client · Grand Vista'), L('Minta pickup, lacak driver menuju property sendiri, ETA, bukti, chat', 'Request pickup, track the driver heading to own property, ETA, evidence, chat')],
      ['nia.hotelabc', L('Klien · Hotel ABC', 'Client · Hotel ABC'), L('Hanya order Hotel ABC; tidak pernah melihat armada atau klien lain', 'Only Hotel ABC orders; never sees the fleet or another client')]
    ].map(function (r) { return ['<code class="p3-code">' + r[0] + '</code>', r[1], r[2]]; })) });
  h += P3.section({ id: 'rules', icon: 'shield', title: L('Aturan wajib (§92)', 'Non-negotiables (§92)'), desc: L('Dari brief Fase 7.', 'From the Phase 7 brief.'), body: P3.dodont(L('Selalu', 'Always'), D.RULES, L('Jangan', 'Never'), D.DONT) });
  h += P3.section({ id: 'backend', icon: 'database', title: L('Catatan untuk tim backend (§90)', 'Note for the backend team (§90)'), desc: L('Apa yang dibuktikan prototipe ini, dan apa yang wajib diulang di server.', 'What this prototype proves, and what the server must repeat.'),
    body: '<div class="p4-note">' + ic('alert') + '<div style="display:grid;gap:var(--jf-space-2)"><p><b>' + t(L('Data Fase 7 adalah data contoh dan posisi driver disimulasikan.', 'Phase 7 data is sample data and driver positions are simulated.')) + '</b> ' + t(L('Semua aturan order, jadwal, dispatch, status, manifest, bukti, masalah, handover, lokasi, ETA, chat, KPI dan audit ada di satu modul (assets/js/jfos-logi.js) yang dipakai aplikasi dan tes. Datanya dari assets/js/jfos-logi-data.js dan disimpan di browser. Klien, property dan SLA dibaca dari engine Fase 6, tidak disalin.', 'Every order, schedule, dispatch, status, manifest, evidence, issue, handover, location, ETA, chat, KPI and audit rule lives in one module (assets/js/jfos-logi.js) shared by the app and the tests. Data comes from assets/js/jfos-logi-data.js and is kept in the browser. Clients, properties and SLA are read from the Phase 6 engine, never copied.')) + '</p>' +
      '<p>' + t(L('Saat backend dibangun: GPS dari HP driver hanya dikirim selama trip aktif; izin, cakupan klien, kepemilikan tugas dan alasan owner diperiksa ulang di setiap API; foto dan tanda tangan disimpan di storage; log akses lokasi dihapus otomatis setelah 30 hari; audit ditulis di server.', 'When the backend is built: GPS from the driver phone is only sent during an active trip; permissions, client scope, task ownership and the owner reason are checked again on every API; photos and signatures go to storage; the location access log is purged automatically after 30 days; the audit is written on the server.')) + '</p></div></div>' });
  h += P3.section({ id: 'dod', icon: 'checkc', title: L('Definition of Done', 'Definition of Done'), desc: L('Checklist §91: setiap butir menunjuk ke bukti. Butir kuning menunggu backend.', '§91 checklist: every item points to its proof. The amber item waits for the backend.'),
    body: '<ul class="p4-dod">' + D.DOD.map(function (d) { return '<li class="' + d[1] + '">' + ic(d[1] === 'done' ? 'checkc' : 'clock') + '<span>' + t(d[0]) + (d[1] === 'backend' ? ' <small class="hint">(' + t(L('menunggu backend', 'waits for backend')) + ')</small>' : '') + '</span><a href="' + d[2] + '" aria-label="' + esc(d[2]) + '"><span>' + t(L('Lihat', 'View')) + '</span>' + ic('arrow') + '</a></li>'; }).join('') + '</ul>' });
  h += P3.section({ id: 'visuals', icon: 'image', title: L('Visual acuan NV-01 sampai NV-10', 'Reference visuals NV-01 to NV-10'), desc: L('Lembar ringkasan dan 10 visual acuan Fase 7.', 'The overview sheet and the 10 Phase 7 reference visuals.'),
    body: '<div class="p5-vis">' + D.VISUALS.map(function (v) { return '<a class="p5-v" href="../assets/brand/phase7/' + v.f + '" target="_blank" rel="noopener"><img src="../assets/brand/phase7/' + v.f + '" alt="" loading="lazy"><b>' + (v.k === 'NV-00' ? 'NV-01–10' : v.k) + '</b><span>' + t(v.t) + '</span></a>'; }).join('') + '</div>' });
  P3.mount('#page', h);
})();
