/* Phase 9 overview: closure model, the three gates, NP-01 … NP-10, demo accounts, rules, backend note, Definition of Done, visuals */
(function () {
  var DS = JFDS, D = JFDLV_DOCS, L = DS.L, t = DS.t, ic = DS.ic, esc = DS.esc, B = DS.Button, M = D.MODEL;
  document.getElementById('herobtns').innerHTML = B.Primary({ label: L('Buka Dispatch Board', 'Open the Dispatch Board'), icon: 'arrow', href: D.go('supervisor', 'DISP-001') }) +
    B.Secondary({ label: L('Sebagai driver', 'As the driver'), icon: 'truck', href: D.go('driver', 'DRV-HO-001') }) +
    B.Ghost({ label: L('Spesifikasi layar', 'Screen specifications'), icon: 'file', href: 'screens.html' }) +
    B.Ghost({ label: L('Kasus uji', 'Test cases'), icon: 'checkc', href: 'tests.html' });
  function chain(list) { return '<div class="p4-flow">' + list.map(function (x, i) { var id = M.links[x]; return (i ? ic('arrow') : '') + (id ? '<a href="screens.html#' + id + '"><span>' + esc(x) + '</span></a>' : '<span>' + esc(x) + '</span>'); }).join('') + '</div>'; }
  var h = '';
  h += P3.section({ id: 'model', icon: 'route', title: L('Model penutupan Fase 9', 'Phase 9 closure model'), desc: L('Dari Siap Kirim sampai Billing Ready. Tracking, driver, rute, ETA dan chat tetap milik Fase 7.', 'From Ready to Deliver to Billing Ready. Tracking, driver, route, ETA and chat stay with Phase 7.'),
    body: '<div style="display:grid;gap:var(--jf-space-4)"><div><b>' + t(L('Alur', 'Flow')) + '</b>' + chain(M.flow) + '</div>' +
      '<div><b>' + t(L('Penutupan JFRESH harus terasa', 'JFRESH closure must feel')) + '</b><ul class="p7-feel">' + M.feel.map(function (f) { return '<li>' + t(f) + '</li>'; }).join('') + '</ul></div></div>' });
  var GATES = [
    [L('Siap ≠ Terkirim', 'Ready ≠ Delivered'), L('Barang baru keluar plant setelah 12 cek release. Trip Fase 7 terkunci sampai release.', 'Goods leave the plant only after the 12 release checks. The Phase 7 trip stays locked until release.'), D.go('supervisor', 'REL-001')],
    [L('Terkirim ≠ Selesai', 'Delivered ≠ Completed'), L('POD valid, rekonsiliasi jelas, tanpa masalah kritis, SLA final. Baru SERVICE COMPLETED.', 'Valid POD, clear reconciliation, no critical issue, final SLA. Only then SERVICE COMPLETED.'), D.go('opsmgr', 'COMP-001')],
    [L('Selesai ≠ Billing Ready', 'Completed ≠ Billing Ready'), L('Kontrak, rate card, tarif historis, qty, diskon, surcharge divalidasi Finance. Lalu dikirim ke Fase 10.', 'Contract, rate card, historical rate, qty, discount, surcharge validated by Finance. Then sent to Phase 10.'), D.go('finance', 'BILL-001')]
  ];
  h += P3.section({ id: 'gates', icon: 'shield', title: L('Tiga gerbang', 'Three gates'), desc: L('Prinsip inti Fase 9, ditegakkan di engine, bukan hanya di tampilan.', 'The core Phase 9 principle, enforced in the engine, not only in the UI.'),
    body: '<div class="p9-gates">' + GATES.map(function (x) { return '<div><b>' + t(x[0]) + '</b><p>' + t(x[1]) + '</p><p style="margin-top:var(--jf-space-2)"><a href="' + x[2] + '">' + t(L('Buka', 'Open')) + ' ' + ic('arrow') + '</a></p></div>'; }).join('') + '</div>' });
  h += P3.section({ id: 'np', icon: 'layers', title: L('10 Bagian NP Fase 9', 'The 10 Phase 9 NP parts'), desc: L('Semua berjalan di aplikasi. Klik untuk langsung ke bagiannya.', 'All of it runs in the app. Click to jump to a part.'),
    body: '<div class="p4-np">' + D.NP.map(function (n) { return '<a href="#' + n.id + '"><span class="l">' + ic(n.ic) + '</span><small>' + n.k + (n.v ? ' · ' + n.v : '') + '</small><b>' + t(n.t) + '</b></a>'; }).join('') + '</div>' });
  D.NP.forEach(function (n, i) {
    h += P3.section({ id: n.id, n: String(i + 1).padStart(2, '0'), title: L(n.k + ' · ' + n.t[0], n.k + ' · ' + n.t[1]), desc: n.d,
      body: '<div class="p4-two"><div style="display:grid;gap:var(--jf-space-4);min-width:0">' + P9.list(n.built) + P9.links(n.links) + '</div><div style="min-width:0">' + P9.ref(n.v) + '</div></div>' });
  });
  h += P3.section({ id: 'demo', icon: 'users', title: L('Akun demo', 'Demo accounts'), desc: L('Password semua akun: jfresh123. Setiap peran melihat menu Fase 9 sesuai haknya.', 'Every account uses jfresh123. Each role sees the Phase 9 menus its rights allow.'),
    body: P3.table([L('Username', 'Username'), L('Peran', 'Role'), L('Yang terlihat di Fase 9', 'What Phase 9 shows')], [
      ['ketut', L('Driver (HP)', 'Driver (mobile)'), L('Delivery hari ini, MULAI PENGIRIMAN, SAYA SUDAH TIBA, serah terima, POD, ADA MASALAH / BUAT RETURN', 'Today\'s deliveries, MULAI PENGIRIMAN, SAYA SUDAH TIBA, handover, POD, ADA MASALAH / BUAT RETURN')],
      ['nyoman.kayana', L('Klien Kayana (HP)', 'Kayana client (mobile)'), L('Pengiriman sendiri, stepper 6 langkah, ETA, peta saat aktif, POD, ORDER COMPLETE, laporan, rating', 'Own deliveries, 6-step stepper, ETA, map while active, POD, ORDER COMPLETE, report, rating')],
      ['saras', L('Supervisor (iPad)', 'Supervisor (iPad)'), L('Release, dispatch, rekonsiliasi, return, masalah, completion, timeline, KPI', 'Release, dispatch, reconciliation, returns, issues, completion, timeline, KPI')],
      ['dewi', L('Operations Manager (desktop)', 'Operations Manager (desktop)'), L('Semua milik supervisor plus amandemen completion dan lihat billing', 'Everything the supervisor has plus completion amendments and billing view')],
      ['budi', L('Finance (desktop)', 'Finance (desktop)'), L('Billing Ready, validasi billing, kirim ke Finance, KPI', 'Billing Ready, billing validation, send to Finance, KPI')],
      ['aji', L('Owner / CEO (desktop)', 'Owner / CEO (desktop)'), L('Dispatch, completion, billing dan dashboard performa (baca saja)', 'Dispatch, completion, billing and the performance dashboard (read only)')],
      ['ayu', L('Sales / Account', 'Sales / Account'), L('Delivery, KPI per klien dan property, feedback klien', 'Deliveries, KPI per client and property, client feedback')],
      ['luh', 'Team 3', L('Antrian siap kirim dan terima return di plant', 'Ready queue and receiving returns at the plant')]
    ].map(function (r) { return ['<code class="p3-code">' + r[0] + '</code>', r[1], r[2]]; })) });
  h += P3.section({ id: 'rules', icon: 'shield', title: L('Aturan wajib (§84)', 'Non-negotiables (§84)'), desc: L('Dari brief Fase 9.', 'From the Phase 9 brief.'), body: P3.dodont(L('Selalu', 'Always'), D.RULES, L('Jangan', 'Never'), D.DONT) });
  h += P3.section({ id: 'backend', icon: 'database', title: L('Catatan untuk tim backend', 'Note for the backend team'), desc: L('Apa yang dibuktikan prototipe ini, dan apa yang wajib diulang di server.', 'What this prototype proves, and what the server must repeat.'),
    body: '<div class="p4-note">' + ic('alert') + '<div style="display:grid;gap:var(--jf-space-2)"><p><b>' + t(L('Data Fase 9 adalah data contoh; jam, GPS dan kamera disimulasikan.', 'Phase 9 data is sample data; the clock, GPS and camera are simulated.')) + '</b> ' + t(L('Semua aturan release, delivery, serah terima, POD, rekonsiliasi, masalah, return, redelivery, completion, SLA, billing, feedback, KPI dan audit ada di satu modul (assets/js/jfos-dlv.js) yang dipakai aplikasi dan tes. Driver, kendaraan, rute, ETA dan chat dibaca dari engine Fase 7; batch dan packing dari Fase 8; kontrak dan rate card dari Fase 6. Tidak ada data yang disalin.', 'Every release, delivery, handover, POD, reconciliation, issue, return, redelivery, completion, SLA, billing, feedback, KPI and audit rule lives in one module (assets/js/jfos-dlv.js) shared by the app and the tests. Driver, vehicle, route, ETA and chat are read from the Phase 7 engine; batches and packing from Phase 8; contracts and rate cards from Phase 6. Nothing is copied.')) + '</p>' +
      '<p>' + t(L('Saat backend dibangun: izin dan isolasi klien diperiksa ulang di setiap API (tombol tersembunyi bukan keamanan); tanda tangan dan foto POD disimpan di storage; POD dan completion beku di server dengan amandemen berversi; antrian offline untuk POD hanya jika benar-benar dibangun, prototipe ini tidak mengklaim POD tersimpan saat offline; payload Billing Ready dikirim ke modul Finance Fase 10.', 'When the backend is built: permissions and client isolation are checked again on every API (hidden buttons are not security); POD signatures and photos go to storage; POD and completion are frozen on the server with versioned amendments; an offline POD queue only if it is really built, this prototype never claims a POD is stored while offline; the Billing Ready payload goes to the Phase 10 Finance module.')) + '</p></div></div>' });
  h += P3.section({ id: 'dod', icon: 'checkc', title: L('Definition of Done', 'Definition of Done'), desc: L('Checklist §83: setiap butir menunjuk ke bukti. Butir kuning menunggu backend.', '§83 checklist: every item points to its proof. The amber item waits for the backend.'),
    body: '<ul class="p4-dod">' + D.DOD.map(function (d) { return '<li class="' + d[1] + '">' + ic(d[1] === 'done' ? 'checkc' : 'clock') + '<span>' + t(d[0]) + (d[1] === 'backend' ? ' <small class="hint">(' + t(L('menunggu backend', 'waits for backend')) + ')</small>' : '') + '</span><a href="' + d[2] + '" aria-label="' + esc(d[2]) + '"><span>' + t(L('Lihat', 'View')) + '</span>' + ic('arrow') + '</a></li>'; }).join('') + '</ul>' });
  h += P3.section({ id: 'visuals', icon: 'image', title: L('Visual acuan Fase 9', 'Phase 9 reference visuals'), desc: L('Lembar acuan NV-01 sampai NV-10 yang dikirim untuk Fase 9.', 'The NV-01 to NV-10 reference sheet sent for Phase 9.'),
    body: '<a class="p9-sheet" href="../assets/brand/phase9/' + D.SHEET + '" target="_blank" rel="noopener"><img src="../assets/brand/phase9/' + D.SHEET + '" alt="NV-01 – NV-10" loading="lazy"></a>' });
  P3.mount('#page', h);
})();
